export interface PanelGuide {
  what: string;
  read: string;
  terms?: readonly string[];
}

export const TERM_DEFINITIONS: Record<string, string> = {
  activation:
    "The 2,688-number hidden state taken from Nano30B layer R33 at one token position.",
  NLA:
    "Natural-language autoencoder: an AV model writes a description of an activation and an AR model reconstructs the activation from that description.",
  AV: "Activation-to-verbalization model. It reads an activation and generates a learned natural-language description.",
  AR: "Activation-reconstruction model, also called the critic. It reads text and predicts an activation vector.",
  RL: "Online reinforcement learning. Here it jointly updated the AV actor and AR critic using rewards from generated activation-to-text-to-activation round trips.",
  critic:
    "The AR reconstruction model used to score whether a description preserves the original activation direction.",
  "learned description":
    "Text generated by the AV model from an activation. It is an encoding produced by a trained model, not a literal transcript of hidden thoughts.",
  teacher:
    "The reference explanation used during supervised training. Re-encoding it provides a strong comparison target.",
  "stored snapshot":
    "An activation saved during dataset construction. Stored-snapshot results compare against that exact archived vector.",
  "fresh forward":
    "An activation recomputed by running Nano30B again. It can differ from the archived snapshot because the execution path is not perfectly identical.",
  control:
    "A deliberately wrong, blank, shuffled, or unrelated input used to test whether the real signal beats a plausible baseline.",
  lane:
    "One matched version of the same intervention: semantic edit, same-meaning paraphrase, random direction, or unedited identity.",
  patch:
    "Replacing Nano30B's activation at a chosen token position with a reconstructed or edited activation before continuing the forward pass.",
  dose:
    "Intervention strength. Dose 0 is the unedited or fidelity reference; larger values apply more of the edit direction.",
  dMSE:
    "Directional mean-squared error. It compares activation direction after removing raw scale; lower is better and 0 means identical direction.",
  cosine:
    "Cosine similarity between two activation vectors. Higher is better; 1 means the directions are identical.",
  "norm ratio":
    "Reconstructed activation length divided by target activation length. A value near 1 preserves magnitude.",
  "AV loss":
    "Average token negative log-likelihood for the explanation text. Lower means the AV model predicts that text more easily.",
  PCA:
    "A validation-fitted two-dimensional projection used only for display. All reported reconstruction metrics are computed in the original 2,688 dimensions.",
  "top-k":
    "The model's k most likely next tokens. Overlap measures how many candidates remain shared after an intervention.",
  "JS divergence":
    "A symmetric distance between next-token probability distributions. Zero means no change; larger values mean more movement.",
  "KL divergence":
    "A directional distance between probability distributions. Larger values mean the patched prediction differs more from the baseline.",
  "confidence interval":
    "A range showing uncertainty across the sampled rows or families, rather than only a single average.",
  "identity retrieval":
    "Whether a reconstructed activation is nearest to its own original row instead of another row in the comparison gallery.",
  "validation-fitted":
    "A threshold or projection selected using validation data. It is exploratory until confirmed on an unopened test set.",
  parse:
    "Whether generated text contained the expected tags and yielded a usable description for scoring.",
  "log-odds":
    "How much more often a word appears in one condition than another after adjusting for its baseline frequency.",
  "identity cosine":
    "Cosine similarity between the reconstruction of a transformed description and the reconstruction of the row's original (identity) description under the same critic. The court compares it with a validation-fitted threshold.",
  "Jaccard overlap":
    "Word-set overlap between two texts: shared distinct words divided by all distinct words either text uses. 1 means identical word sets; 0 means none shared.",
  canary:
    "A tiny early-warning subset run before the full experiment. Its numbers sanity-check the pipeline; the population claim rests on the full-size report.",
};

interface GuideRule {
  matches: readonly string[];
  guide: PanelGuide;
}

const RULES: readonly GuideRule[] = [
  {
    matches: ["did online rl improve reconstruction"],
    guide: {
      what: "Compares the clean SFT checkpoint with the selected online-RL actor and critic on exactly the same 122 held-out validation families and 384-token generation protocol.",
      read: "Start with the large before-and-after error: lower is better. Then confirm that raw error also falls, parsing remains healthy, and the real matching activation beats every bad-input control. Treat this as a joint AV+AR validation result, not a sealed test.",
      terms: ["RL", "AV", "AR", "dMSE", "teacher", "control", "parse"],
    },
  },
  {
    matches: ["selected row: source"],
    guide: {
      what: "Connects one complete validation source to the learned AV description generated from its stored R33 activation, the AR reconstruction scores, and the teacher reference.",
      read: "Choose an example above the left pane, read the full source, then move right to the learned description. The critic selector changes only the reconstruction scoring; it does not regenerate the displayed AV text.",
      terms: ["activation", "AV", "AR", "learned description", "dMSE", "identity retrieval"],
    },
  },
  {
    matches: ["information waterfall"],
    guide: {
      what: "Compares how accurately the AR critic reconstructs the same stored activation from teacher text, learned AV descriptions, and deliberately uninformative controls.",
      read: "Shorter bars are better. The key comparison is learned description versus teacher and every gray control; similar learned and teacher bars mean the generated language retained nearly as much direction as the reference text.",
      terms: ["AV", "AR", "critic", "teacher", "control", "dMSE", "stored snapshot"],
    },
  },
  {
    matches: ["real-vs-control av loss"],
    guide: {
      what: "Tests whether explanation tokens are easier for the AV model to predict — lower autoregressive token loss — when it receives the correct activation rather than a blank, mean, shuffled, or absent activation.",
      read: "Lower loss is better. The blue real bar should sit left of every control, and 'real wins' should remain high across rows; this shows conditioning signal, not semantic truth by itself.",
      terms: ["AV", "AV loss", "activation", "control", "canary"],
    },
  },
  {
    matches: ["twin critics"],
    guide: {
      what: "Re-encodes the same descriptions with two separately trained AR critics to check whether the reconstruction result depends on one scorer.",
      read: "Points near the diagonal mean both critics rank the rows similarly. Agreement is reassuring, but both critics share the same teacher data, so they are not fully independent semantic judges.",
      terms: ["AR", "critic", "dMSE", "cosine", "teacher"],
    },
  },
  {
    matches: ["capacity ladder"],
    guide: {
      what: "Asks how often a reconstructed activation can identify its source when the number of possible source rows grows from 2 to 256.",
      read: "Higher accuracy is better. A slowly falling curve means descriptions preserve enough row-specific information to distinguish among larger galleries; this is a retrieval lower bound, not a literal channel-capacity measurement.",
      terms: ["identity retrieval", "activation", "learned description"],
    },
  },
  {
    matches: ["retrieval"],
    guide: {
      what: "Checks whether each reconstructed activation is closest to its own stored target rather than a different row.",
      read: "Rank 1 is a correct identity match. Inspect the visible misses as important negative cases rather than treating aggregate accuracy as universal success.",
      terms: ["identity retrieval", "activation", "stored snapshot"],
    },
  },
  {
    matches: ["words buy direction"],
    guide: {
      what: "Truncates the teacher reference explanation to different word budgets and measures how much reconstruction quality each additional block of language buys.",
      read: "Move from left to right. Falling dMSE or rising cosine means extra words carry useful activation information; a plateau marks diminishing returns.",
      terms: ["teacher", "dMSE", "cosine"],
    },
  },
  {
    matches: ["attribution"],
    guide: {
      what: "Removes selected words or sections from a description, re-encodes the remainder, and measures which parts mattered for reconstruction.",
      read: "A larger error increase after removal means that text span carried more direction-relevant information. This is deletion sensitivity, not proof that the phrase names a causal model feature.",
      terms: ["AR", "dMSE", "learned description"],
    },
  },
  {
    matches: ["alternate-tellings fan"],
    guide: {
      what: "Shows several independently generated descriptions of the same activation and compares how consistently they reconstruct it.",
      read: "Look for semantic variation with stable reconstruction scores. Wide score spread means wording choice materially changes the code; tight spread suggests redundancy across tellings.",
      terms: ["AV", "AR", "activation", "dMSE"],
    },
  },
  {
    matches: ["rewrite"],
    guide: {
      what: "Transforms a learned description with format-preserving rewrites and corruptions, then measures whether format changes retain more activation direction than destructive edits.",
      read: "A robust language code should tolerate format rewrites while failing under meaning-destroying corruption. Compare each rewrite with the original row, not only with an absolute threshold.",
      terms: ["learned description", "AR", "dMSE", "validation-fitted", "identity cosine"],
    },
  },
  {
    matches: ["document token-linked nla reader"],
    guide: {
      what: "Shows the full released document with every sampled activation position highlighted in place, beside the AV text generated from the selected token's activation.",
      read: "Choose a highlighted token directly inside the document on the left; the right pane updates to its NLA verbalization. Plain text was not sampled for this dashboard. One source trajectory cannot be aligned and is labeled rather than guessed.",
      terms: ["activation", "AV", "learned description", "fresh forward", "parse"],
    },
  },
  {
    matches: ["learned description"],
    guide: {
      what: "Displays the natural-language code emitted by AV for the activation at the selected token position.",
      read: "Treat the text as a decoder readout. Specific, repeated concepts are interesting signals, but a single fluent description is not evidence that the base model verbalized or consciously represented them.",
      terms: ["AV", "activation", "learned description", "parse"],
    },
  },
  {
    matches: ["persistence of adjacent descriptions"],
    guide: {
      what: "Measures how much the learned description changes from one token position to the next within a document, as Jaccard word overlap between adjacent descriptions.",
      read: "High overlap indicates a persistent theme; additions and deletions show where the readout changes. There is no chance baseline in this bundle, so read values comparatively across transitions, not against a threshold.",
      terms: ["learned description", "fresh forward", "Jaccard overlap"],
    },
  },
  {
    matches: ["real-vs-shuffled control"],
    guide: {
      what: "Compares the selected token's description with descriptions attached to mismatched positions or documents.",
      read: "The real pairing should be more coherent with its prefix than shuffled pairings. If both look equally plausible, the apparent trace may be generic decoder language.",
      terms: ["control", "learned description", "fresh forward"],
    },
  },
  {
    matches: ["fresh-vs-stored drift", "fresh-forward drift"],
    guide: {
      what: "Quantifies how much a newly recomputed activation differs from the archived activation used as the dataset target.",
      read: "Zero would mean exact reproduction. Nonzero drift limits claims that transfer stored-snapshot reconstruction results to new forwards, even when cosine direction remains high.",
      terms: ["fresh forward", "stored snapshot", "cosine", "activation"],
    },
  },
  {
    matches: ["token-linked poetry nla reader"],
    guide: {
      what: "Shows the complete poetry prefix with every analyzed token selectable in place, beside four real AV verbalizations and two shuffled-activation controls for the selected token.",
      read: "Choose a highlighted token in the left text. Tokens after it are marked as not yet seen at that activation; the held-out second line was never supplied. Compare the real and shuffled NLA samples on the right before interpreting apparent rhyme planning.",
      terms: ["activation", "AV", "learned description", "fresh forward", "control"],
    },
  },
  {
    matches: ["prefix and analysis window"],
    guide: {
      what: "Shows exactly which tokens Nano30B had already seen at each poetry-analysis position and marks the future rhyme anchor that was still hidden.",
      read: "Offsets count backward from the anchor. A signal at a negative offset occurs before the target rhyme token enters the context.",
      terms: ["activation", "fresh forward"],
    },
  },
  {
    matches: ["planning-onset curve"],
    guide: {
      what: "Plots how often AV descriptions mention the future target-rhyme family at each position before the anchor token.",
      read: "Blue is the real prefix and gray is a shuffled-prefix control. An early blue rise above the dashed threshold is suggestive; the small sample and failed causal edit keep it exploratory.",
      terms: ["AV", "control", "fresh forward"],
    },
  },
  {
    matches: ["av samples"],
    guide: {
      what: "Shows the individual AV descriptions whose target-term matches are summarized by the planning-onset curve.",
      read: "Underlined words triggered the automated score. Read the surrounding sentence to distinguish a meaningful anticipation from a generic or accidental word match.",
      terms: ["AV", "learned description", "control"],
    },
  },
  {
    matches: ["baseline continuation"],
    guide: {
      what: "Shows Nano30B's unpatched continuation from the selected poetry prefix.",
      read: "This is the behavioral reference. It tells you whether the model naturally lands in the target rhyme family before any activation edit.",
      terms: ["patch", "control"],
    },
  },
  {
    matches: ["causal edit bench"],
    guide: {
      what: "Changes rhyme-related words in the learned description, reconstructs an activation, patches it into Nano30B, and observes the continuation.",
      read: "A causal success requires the edited direction to produce the alternate rhyme while dose 0 and the norm-matched random control do not. Movement alone is not success.",
      terms: ["learned description", "AR", "patch", "dose", "control"],
    },
  },
  {
    matches: ["all cases"],
    guide: {
      what: "Keeps every poetry case visible, including zero lifts, absent onsets, baseline misses, and failed steering attempts.",
      read: "Use the cards to judge consistency rather than selecting the most vivid example. The bottom summary is the population result for this small exploratory set.",
      terms: ["control", "fresh forward"],
    },
  },
  {
    matches: ["row + move picker"],
    guide: {
      what: "Selects one stored validation row, one language edit, and one intervention strength from the precomputed experiment grid.",
      read: "Every choice updates all panels below to the same experiment. METRIC cells contain reconstruction scores; BEHAVIOR cells also contain patched next-token and continuation results.",
      terms: ["lane", "dose", "patch", "stored snapshot"],
    },
  },
  {
    matches: ["control rack"],
    guide: {
      what: "Places the semantic edit beside three required comparisons: a same-meaning paraphrase, a norm-matched random direction, and the unedited teacher encoding.",
      read: "Read horizontally. A credible semantic effect should differ from the paraphrase and random lanes while the identity lane establishes the reconstruction floor.",
      terms: ["lane", "control", "teacher", "dMSE", "cosine", "norm ratio"],
    },
  },
  {
    matches: ["reconstruction compass"],
    guide: {
      what: "Projects the target and four reconstructed activation directions into two dimensions so their relative geometry can be inspected.",
      read: "Nearby points are visually similar in the fitted projection, but use the table's native 2,688-dimensional dMSE and cosine for conclusions; PCA can distort distances.",
      terms: ["PCA", "activation", "dMSE", "cosine", "lane"],
    },
  },
  {
    matches: ["next-token top-k movement"],
    guide: {
      what: "Compares Nano30B's most likely next tokens before and after each reconstructed activation is patched into the model.",
      read: "New, lost, and reordered tokens reveal what changed locally. Lower overlap means more movement, but a useful edit must still separate from placebo and random controls.",
      terms: ["top-k", "patch", "lane", "control"],
    },
  },
  {
    matches: ["divergence gauges"],
    guide: {
      what: "Summarizes how far each patched next-token distribution moved from the unpatched baseline using several complementary distances.",
      read: "Longer JS and KL bars mean more distribution change; lower top-k overlap also means more change. Compare the edit with every control rather than maximizing movement.",
      terms: ["JS divergence", "KL divergence", "top-k", "patch", "control"],
    },
  },
  {
    matches: ["causal wake"],
    guide: {
      what: "Tracks how the effect of one activation patch propagates across later token offsets under teacher forcing.",
      read: "A spike at the first offset after the patch is the immediate intervention (the trace starts at offset 1). A sustained non-control difference at later offsets would indicate persistence; a rapid return to zero means a short local wake.",
      terms: ["patch", "lane", "JS divergence", "KL divergence"],
    },
  },
  {
    matches: ["continuations"],
    guide: {
      what: "Places the unpatched continuation beside the continuation produced after the selected reconstructed activation is patched into Nano30B.",
      read: "Highlighted words changed between outputs. Read for semantic direction and fluency, then check the control lanes before attributing the difference to the intended edit.",
      terms: ["patch", "lane", "control"],
    },
  },
  {
    matches: ["dose comparison"],
    guide: {
      what: "Shows whether behavioral movement changes systematically as intervention strength increases.",
      read: "A smooth edit-specific response is more credible than a one-off jump. Flat placebo and identity lines are useful controls; a matching random line weakens the semantic interpretation.",
      terms: ["dose", "lane", "control", "JS divergence", "KL divergence"],
    },
  },
  {
    matches: ["session ledger"],
    guide: {
      what: "Records which precomputed experiment cells you opened during this browser session.",
      read: "Use it as a reproducibility trail when comparing examples. It stores identifiers and selections only; it is not an additional experiment result.",
      terms: ["lane", "dose"],
    },
  },
  {
    matches: ["claim ledger"],
    guide: {
      what: "States the strongest claim each evidence family is currently allowed to support.",
      read: "The status label is the conclusion boundary: qualified can be reported as validated here, exploratory needs confirmation, and not-opened test evidence must not be inferred.",
      terms: ["stored snapshot", "fresh forward", "validation-fitted"],
    },
  },
  {
    matches: ["negative & weak results"],
    guide: {
      what: "Collects failed, weak, and caveated findings beside the positive results so the dashboard cannot silently select successes.",
      read: "Treat each row as a limit on the story. These outcomes determine which attractive interpretations are not currently supported.",
      terms: ["control", "fresh forward", "stored snapshot"],
    },
  },
  {
    matches: ["parse health & control completeness"],
    guide: {
      what: "Checks that generated descriptions were parseable and that every required control condition is present before metrics are interpreted.",
      read: "Usable and closed rates should be near 100%. Missing parses or missing controls reduce the valid sample rather than counting as successful evidence.",
      terms: ["parse", "control", "AV"],
    },
  },
  {
    matches: ["cipher court docket"],
    guide: {
      what: "Applies validation-fitted thresholds to decide whether paraphrases preserve the code and heavy corruptions break it on each row.",
      read: "Balanced accuracy summarizes the fitted rule, while the full docket exposes row-level exceptions. Paraphrases are expected to preserve the code and heavy corruption is expected to break it — a preserved heavy corruption is the suspicious outcome. The shared teacher target means this is a calibrated robustness test, not an independent semantic oracle.",
      terms: ["validation-fitted", "AR", "critic", "teacher", "identity cosine"],
    },
  },
  {
    matches: ["magnitude card"],
    guide: {
      what: "Separates activation direction from activation length to show how different magnitude calibrations affect reconstruction.",
      read: "Direction metrics can look good while norm ratio is wrong. Use centered R-squared and norm ratio to judge magnitude; this post-hoc validation view is not confirmatory test evidence.",
      terms: ["activation", "dMSE", "cosine", "norm ratio"],
    },
  },
  {
    matches: ["null-text almanac"],
    guide: {
      what: "Finds words disproportionately generated from real activations versus a zero-vector control, revealing systematic decoder vocabulary biases.",
      read: "Positive blue log-odds favor real activations; gray terms favor the zero control. Frequent generic words can expose a decoder prior rather than meaningful row-specific content.",
      terms: ["AV", "control", "log-odds", "activation"],
    },
  },
  {
    matches: ["poetry pipeline status"],
    guide: {
      what: "Reports which poetry-analysis phases completed and binds the displayed results to the exact configuration hash.",
      read: "Completion means the pipeline ran, not that the planning hypothesis succeeded. The scientific outcome remains the weak signal and negative causal result shown in TRACE.",
      terms: ["fresh forward", "control"],
    },
  },
  {
    matches: ["provenance browser"],
    guide: {
      what: "Lists the source reports, configuration hashes, runtime versions, exclusions, and privacy status behind every dashboard number.",
      read: "Use hashes to reproduce or audit a view. A visible source binding is evidence provenance, not an endorsement of the underlying claim.",
      terms: ["validation-fitted", "stored snapshot", "fresh forward"],
    },
  },
  {
    matches: ["row evidence"],
    guide: {
      what: "Reports whether the selected row has the precomputed evidence required by the BENCH panels.",
      read: "An unavailable state is a real coverage boundary. Choose a BEHAVIOR-depth row for functional panes; the interface never invents or substitutes missing cells.",
      terms: ["lane", "patch"],
    },
  },
  {
    matches: ["cross-station"],
    guide: {
      what: "Connects this token-level trace to related precomputed reconstruction or intervention evidence elsewhere in the dashboard.",
      read: "Follow the link only when the same row identity is available. Absence is shown explicitly and should not be treated as a negative experimental result.",
      terms: ["activation", "stored snapshot", "fresh forward"],
    },
  },
];

export function panelGuideFor(title: string): PanelGuide | null {
  const normalized = title.toLowerCase();
  return RULES.find((rule) => rule.matches.some((match) => normalized.includes(match)))?.guide ?? null;
}
