/**
 * Static shard loader. All evidence is local static JSON generated by
 * scripts/build_static_data.py; there is no other network surface.
 *
 * Loading policy:
 *  - the manifest loads first and gates everything (schema check);
 *  - station shards load lazily on demand and are cached forever;
 *  - a failed or malformed shard yields an explicit error state — the app
 *    never silently substitutes mock values for missing evidence.
 */

import { useEffect, useState } from "react";
import type { DashboardManifest } from "./types";

export const DATA_BASE = "data";
export const EXPECTED_SCHEMA = "nla_observatory_dashboard.v2";

export type LoadState<T> =
  | { status: "loading" }
  | { status: "error"; message: string }
  | { status: "ready"; data: T };

const cache = new Map<string, Promise<unknown>>();
let manifestPromise: Promise<DashboardManifest> | null = null;

async function fetchJson<T>(path: string): Promise<T> {
  const res = await fetch(`${DATA_BASE}/${path}`, { cache: "no-cache" });
  if (!res.ok) {
    throw new Error(`failed to load ${path}: HTTP ${res.status}`);
  }
  let body: unknown;
  try {
    body = await res.json();
  } catch {
    throw new Error(`malformed JSON in ${path}`);
  }
  return body as T;
}

export async function loadManifest(): Promise<DashboardManifest> {
  if (!manifestPromise) {
    manifestPromise = fetchJson<DashboardManifest>("manifest.json").then((manifest) => {
      if (manifest.schema_version !== EXPECTED_SCHEMA) {
        throw new Error(
          `bundle version mismatch: expected ${EXPECTED_SCHEMA}, got ${manifest.schema_version}. ` +
            "Re-run scripts/build_static_data.py.",
        );
      }
      return manifest;
    });
    manifestPromise.catch(() => {
      manifestPromise = null;
    });
  }
  return manifestPromise;
}

export function loadShard<T extends { schema_version: string }>(path: string): Promise<T> {
  let pending = cache.get(path) as Promise<T> | undefined;
  if (!pending) {
    pending = (async () => {
      const manifest = await loadManifest();
      const entry = manifest.files.find((f) => f.path === path);
      if (!entry) {
        throw new Error(`shard ${path} is not listed in the dashboard manifest`);
      }
      const shard = await fetchJson<T>(path);
      if (
        typeof shard !== "object" ||
        shard === null ||
        !("schema_version" in shard) ||
        (shard.schema_version !== EXPECTED_SCHEMA && entry.schema_version !== "source_copy.v1")
      ) {
        throw new Error(`shard ${path} failed its schema check`);
      }
      return shard;
    })();
    cache.set(path, pending);
    pending.catch(() => cache.delete(path));
  }
  return pending;
}

export function useShard<T extends { schema_version: string }>(path: string | null): LoadState<T> {
  const [state, setState] = useState<LoadState<T>>({ status: "loading" });
  useEffect(() => {
    if (path === null) return;
    let alive = true;
    setState({ status: "loading" });
    loadShard<T>(path)
      .then((data) => alive && setState({ status: "ready", data }))
      .catch((err: Error) => alive && setState({ status: "error", message: err.message }));
    return () => {
      alive = false;
    };
  }, [path]);
  return state;
}

export function useManifest(): LoadState<DashboardManifest> {
  const [state, setState] = useState<LoadState<DashboardManifest>>({ status: "loading" });
  useEffect(() => {
    let alive = true;
    loadManifest()
      .then((data) => alive && setState({ status: "ready", data }))
      .catch((err: Error) => alive && setState({ status: "error", message: err.message }));
    return () => {
      alive = false;
    };
  }, []);
  return state;
}

/** Test hook: reset module caches between unit tests. */
export function resetLoaderForTests(): void {
  cache.clear();
  manifestPromise = null;
}
